[package]
name = "fat32"
version = "0.2.0"
edition = "2021"

[dependencies]
# lazy_static = { version = "1.4.0", features = ["spin_no_std"] }
spin = "0.9.2"
lru = "0.12.3"
riscv = "0.11.1"
log = "0.4"

time_tracer = { path = "../time_tracer" }

[features]
time_tracer = []
