[package]
name = "cv1812h-sd"
version = "0.1.0"
edition = "2021"
base = "https://github.com/Byte-OS/cv1811-sd"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bit-struct = "0.3.2"
log = "0.4"